pref("extensions.faext.download.directory","");
pref("extensions.faext.download.newdir",true);
pref("extensions.faext.download.prettyartist",false);
pref("extensions.faext.download.auto",false);
pref("extensions.faext.openintabs.delay",true);
pref("extensions.faext.openintabs.delaytime",2);
pref("extensions.faext.openintabs.reverse",true);
pref("extensions.faext.hotkeys.enable",false);
pref("extensions.faext.colornotification.enable",false);